# Generated by Django 5.1.2 on 2024-12-09 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walkary', '0003_walkdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalkData',
        ),
    ]
